### ISSUE TITLE
Pale Oak Sapling cannot grow

### ISSUE THREAD

**Issue by SAGUMEDREAM** [Onako2/i-want-it-earlier#2]
I discovered that Pale Oak Sapling cannot grow.

According to the code about ConfiguredFeature definition, I checked the file directory data/iwie/worldgen/configured_feature/ and found no pale_tree.json file;

`public static final SaplingGenerator PALE;`
`public static final RegistryKey<ConfiguredFeature<?, ?>> PALE_REGISTRY = RegistryKey.of(RegistryKeys.CONFIGURED_FEATURE, Identifier.of("iwie", "pale_tree"));`
`static {PALE = new SaplingGenerator("pale_tree", Optional.of(PALE_REGISTRY), Optional.empty(), Optional.empty());}`

**Comment by Onako2** [comment]
Thanks for reporting! I'll fix it soon or do you want to create a PR (Modtoberfest)
