### ISSUE TITLE
1.20.4 ?

### ISSUE THREAD

**Issue by Anonyku05** [Onako2/i-want-it-earlier#6]
Title :D

**Comment by Onako2** [comment]
Hi, could you please be more precise?

**Comment by Anonyku05** [comment]
Sorry for confusion, wanted to ask if this mod is planned to be on 1.20.4

**Comment by Onako2** [comment]
You mean with the Pale garden stuff or the Trial chambers?
Currently neither of them is planned because of internal stuff and I don't want to make the mod from scratch
